runners:
  - name: cirun-gcp-aarch64-runner
    cloud: gcp
    instance_type: n4a-standard-32
    machine_image: cos-arm64-129-19506-120-64
    region: us-east1-b
    preemptible: true
    extra_config:
      baseDisk:
        diskSizeGb: 60
    labels:
      - cirun-gcp-aarch64

  - name: cirun-gcp-x86-runner
    cloud: gcp
    instance_type: c4d-standard-32
    machine_image: cos-129-19506-120-64
    region: us-east1-b
    preemptible: true
    extra_config:
      baseDisk:
        diskSizeGb: 60
    labels:
      - cirun-gcp-x86
